### ISSUE TITLE
No more arm64 image in docker hub

### ISSUE THREAD

**Issue by AlphaJack** [souramoo/commentoplusplus#113]
I cannot find anymore the arm64 version of the docker image:

![image](https://user-images.githubusercontent.com/19962243/181608404-5452e9f9-bb07-496c-b5cb-c1f408294c70.png)
![image](https://user-images.githubusercontent.com/19962243/181608482-f88d665b-4992-472f-b16f-7dc2485791de.png)

**Comment by souramoo** [comment]
This is expected as described by https://github.com/souramoo/commentoplusplus/pull/89#issuecomment-1091696774

If you have any suggestions on how to fix the build process errors caused by missing binaries in the arm64 images we base ourselves on, please do open a pull request and I'd love to merge it!
