### ISSUE TITLE
Multiple domain for a single project

### ISSUE THREAD

**Issue by MexsonFernandes** [souramoo/commentoplusplus#13]
First of all thanks for keeping it alive. I have bit of issue with my configuration. Can we have configuration for a single project base with multiple domains? rather than each domain attached to each project?

For example, if I have `app.domain.com` the comments would load fine. But if I deploy this on mobile app the comments would not show since origin is different. So do I have any solution for this?

**Comment by FrancisTurner** [comment]
I'd like to add my voice to requesting this. Another specific usecase is when you have www.domain.com and domain.com both pointing to the same blog. Obviously you can return a 302 redirect from one but it would be nice if you could have both just work with commento++ instead.

**Comment by souramoo** [comment]
Good suggestion! I will think a bit about how best to implement it (both technically and from the UI side of things) and see what I can do!

**Comment by FrancisTurner** [comment]
OK here's what I would like. An option to have wildcard support for all subdomains when creating the new comment domain in commento. This could be either done be specifying *.domain.com in the domain name or by a check box.

![image](https://user-images.githubusercontent.com/991242/111246170-18dd1580-8606-11eb-8048-ce7ccf2b0842.png)

![image](https://user-images.githubusercontent.com/991242/111246226-2c887c00-8606-11eb-950f-89dc3bfe753b.png)

That's the UI part. Implementation looks like it would be a conditional change to a couple of queries to simplify or even remove the domain check. i.e. remove the comment.domain=$1 section of the various select where queries. But I'm probably missing things. 

I would be quite happy to have as a limitation that a commento++ instance with wildcard domain support can only have one active domain because in the usecase I'm thinking of, the commento++ instance will only be supporting a single (ghost) blog

**Comment by souramoo** [comment]
Thanks for the helpful input! I've now added this feature as of 93c05e9 - you can disable it with an environment variable but should be on by default.

You just need to use % instead of * because that's what PostgreSQL likes - so you should be able to now use `%.domain.com` to get `app.domain.com` and `www.domain.com`.

You can also now convert your entire commento instance to only serve a single source of comments regardless of domain by registering `%` as your domain name,

Have fun! Please report back if you experience any bugs, since this is quite a new feature. I've tried my best to think through the edge-cases and added stronger domain canonicalisation to prevent you adding two domains that will conflict with one another.

If you want to change the domain name for an existing domain, please edit the `domain` column of the corresponding entry in the `domains` table in your PostgreSQL instance using a client e.g. HeidiSQL (but be careful!).

**Comment by EarthMan123** [comment]
@souramoo 

> You can also now convert your entire commento instance to only serve a single source of comments regardless of domain by registering `%` as your domain name, but be warned this will allow any website to embed your commento instance so I would strongly suggest restricting it to your domain name in some way!

Tried this one and it didn't work. I'm trying to test it from a local static site beforr publishing and wanted to allow all  to access to do so.
