### ISSUE TITLE
Web vitals errors

### ISSUE THREAD

**Issue by TannerGabriel** [souramoo/commentoplusplus#51]
First, thank you for all the work on the project. That said, I have found a few bugs/problems when running a [website performance test](https://web.dev/measure/) that should be addressed.

![Cross origin destination unsafe](https://user-images.githubusercontent.com/40315960/126066577-cbbc4ea1-1598-4e97-8436-34cfca5976a2.png)

This can be fixed by adding the named parameters to the `a` tag in [this line](https://github.com/souramoo/commentoplusplus/blob/8e1c4bb8e4f55889e7a4f6af3a80c41de1c56d42/frontend/js/commento.js#L448). I could make a PR for this if that is ok with you.

The following error could be a bit harder to debug as it has something to do with WebSockets, but it is not easily reproducible when trying manually. Let me know if you have any ideas about this.

![Socket errors](https://user-images.githubusercontent.com/40315960/126066835-89966d47-3af4-4c49-aa69-d12c31cec57b.png)

**Comment by souramoo** [comment]
Hey,
Thanks for looking into this! I'd be more than happy to accept a PR for this :)

The websocket error is weird - I've tried to do a bit of research on it and it seems it's quite common and likely because the web.dev firewall blocks websocket connections during the test (https://stackoverflow.com/questions/59157106/unable-to-reproduce-web-dev-console-errors) but are safely ignored.

**Comment by TannerGabriel** [comment]
@souramoo If we can safely ignore the WebSockets errors, I see no problem in closing the issue.
