### ISSUE TITLE
Migrate from Commento to Commento++

### ISSUE THREAD

**Issue by ErminMerdanovic** [souramoo/commentoplusplus#94]
Hi guys, I just wanted to know if it's possible to migrate from Commento to Commento++ without any problems. Or are there problems that may arise, e.g. B. with the database or anything else?

**Comment by souramoo** [comment]
There shouldn't be; all the added migrations should take any commento install and upgrade it without any issues. Do check the environment variables in the readme for any behaviour that will have changed e.g. for logging view counts that are disabled by default instead of enabled by default but this can be easily reverted if desired. If you do encounter any problems please do let me know!

**Comment by gilromano** [comment]
Thank you sooo much for keeping this project alive!  I think it's time for me to migrate my existing commento cloud hosted instance to commentoplusplus.  I didn't see anything when I looked, but are there any walkthrough instructions on how to perform that migration?
