### ISSUE TITLE
Import from Commento does not work

### ISSUE THREAD

**Issue by sahava** [souramoo/commentoplusplus#97]
Hi!

I've exported my Commento.io database as .json.gz, and I've uploaded the file to a public URL.

I then go to my Heroku Commento instance, and via Admin -> Import Comments -> Commento I add the URL and click Import.

The network request takes ~35-40 seconds, after which it gets a 200 success result, but the response is `{"message":"That email address has already been registered.","success":false}`. When I look into the postgre database, there are no new rows added.

One time I tried it the request timed out and the postgre database had a couple of thousand new rows, but I still saw no comments in my Heroku Commento instance.

Is there some way to debug this import process or to run it in a CLI with the .json.gz to help debug it further?

Thank you!

**Comment by souramoo** [comment]
Please cold you post the logging output? If you install the free papertrail addon you should be able to get the logs, alternatively you can get them from the heroku console directly (but they do not save if you go off the page). With this we can work out exactly what the problem is, I think it may well be trying to add an email address that already exists in your commento++ user table (I should make the import process ignore this if so). Then once we are sure what the issue is, we can try cleaning out the database and then trying the re-import again :)

**Comment by sahava** [comment]
Hi

It started working even with the error message :/ I think it was because I had registered an email as admin that was already a commenter in the import.
